name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Upload to OSS
        uses: tvrcgo/upload-to-oss@v0.1.1
        with:
          region: oss-cn-shanghai
          key-id: ${{secrets.ACCESSKEY_ID}}
          key-secret: ${{secrets.ACCESSKEY_SECRET}}
          bucket: wzb-resume
          asset-path: ./pdf
          target-path: /
